### ISSUE TITLE
Ensure .env keycloak config is fully effective

### ISSUE THREAD

**Issue by LBBO** [TUM-DiStaT/stochus#45]
Some of the keycloak config is redundantly set in the [`docker/keycloak/realms/stochus.json`](https://github.com/TUM-DiStaT/stochus/blob/main/docker/keycloak/realms/stochus.json). The values set in the JSON file should be ignored in the presence of the environment values.

## TODO
- [ ] Check if this is the case or not. If not, fix it.
- [ ] Ideally figure out how to permanently remove redundant (and especially secret) values from the JSON. Ensure the values aren't re-introduced by an export
- [ ] Update the Keycloak configuration wiki page.
